### ISSUE TITLE
Keep teminal open ?

### ISSUE THREAD

**Issue by bsdev90** [nicollasricas/streamdeckvsc#12]
Hi,

I added a "Create Terminal" action to launch NodeJS script with path "C:\Program Files\nodejs\node.exe" and argument "app.js".
The button works and fire a terminal which launch the app (Whatever the project, I almost always call my file "app.js").

The problem is that when an application terminates (whether due to an error or manually), the terminal closes so not verry easy to read the error...
Is there a way to keep the terminal open ?

**Comment by nicollasricas** [comment]
Hey,

I did some testing and I think the reason the terminal closes it's because the path, which in this case is NodeJS, acts as the shell for the terminal.

Is there a reason for you to be using the create terminal action instead of execute terminal command action?

![image](https://user-images.githubusercontent.com/7860985/207758691-dd415f44-7e5c-48d5-af40-0471a515f2b5.png)

** To use the execute terminal command, you need to have at least one active terminal. It should have at least one by default, but if for any reason you close it accidentally, you can just open a new one and everything will work just fine.

This was fixed in the new version that I'm extensively testing before releasing, since I rewrote the entire thing.

Best,
Nicollas

**Comment by bsdev90** [comment]
Hi,

Thank for the fast answer ! Of course there is a reason... no, there is no reason. I just didn't notice the existence of this action 
(even though it is the one with the longest name!)... I had to go too fast, being in full discovery of the Stream Deck.

Sorry for the inconvenience and I take this opportunity to say thank you for this plugin, it will save me a lot of time!

**Comment by nicollasricas** [comment]
> Of course there is a reason... no, there is no reason.

kkkkkkkkkkkkk. Glad it worked. If you need any assistance, just let me know.
