### ISSUE TITLE
Multi-Action Support

### ISSUE THREAD

**Issue by Zendrex** [nicollasricas/streamdeckvsc#2]
Unsure on the level of complexity this is, however it would be nice to have this ability. I saw this in the WIP section, however without an update in multiple months, wasn't sure if this project was deprecated.

**Comment by nicollasricas** [comment]
Next update will be released soon with multi-action support included.

I've been using this every day since the day I made it so it won't be deprecated at any time soon.

**Comment by nicollasricas** [comment]
Could you share your use case for multi-action?

**Comment by Zendrex** [comment]
Personally I have some projects that require multiple project terminals, so my goal was to the multi-action support to initialize a terminal, focus, run a command, split, run a command. (ex: start a nuxt instance and node server with one tap of a button)

**Comment by nicollasricas** [comment]
Hey,

I just enabled actions to have support to multi-action.

I couldn't manage to get multi-action working without using delay since Stream Deck SDK doesn't have any control over actions running state.

Your case should work just fine with a few delays. Made a simple example:

![image](https://user-images.githubusercontent.com/7860985/75173459-473f3880-5705-11ea-9ad4-d24ce549adec.png)

**Comment by Zendrex** [comment]
[![Screenshot from Gyazo](https://gyazo.com/3b1bd378865f21cfd93f667321339ff1/raw)](https://gyazo.com/3b1bd378865f21cfd93f667321339ff1)

Works Great, much appreciated.

**Comment by nicollasricas** [comment]
I'm glad it worked.
